### ISSUE TITLE
windows 下 nginx 的安装及使用 | 代码改变世界

### ISSUE THREAD

**Issue by l-ff** [l-ff/blog#12]
https://blog.geek-arno.top/windows%E4%B8%8Bnginx%E7%9A%84%E5%AE%89%E8%A3%85%E5%8F%8A%E4%BD%BF%E7%94%A8/

**Comment by Geek-Arno** [comment]
🛋🛋🛋

**Comment by Geek-Arno** [comment]
🛋🛋🛋🛋🛋🛋
